version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    commit-message:
      prefix: meta
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: '/'
    versioning-strategy: increase
    schedule:
      interval: monthly
    commit-message:
      prefix: meta
    groups:
      next-js:
        patterns:
          - 'next*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      tailwind:
        patterns:
          - 'tailwindcss'
      heroicons:
        patterns:
          - '@heroicons/react'
      radix-ui:
        patterns:
          - '@radix-ui/*'
    ignore:
      # Manually update major versions of @types/node with the version specified within .nvmrc
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
    open-pull-requests-limit: 10
